[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  NODE_VERSION = "20"
  VITE_FIREBASE_API_KEY = ""
  VITE_FIREBASE_AUTH_DOMAIN = "alice-tattoos.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "alice-tattoos"
  VITE_FIREBASE_STORAGE_BUCKET = "alice-tattoos.firebasestorage.app"
  VITE_FIREBASE_MESSAGING_SENDER_ID = ""
  VITE_FIREBASE_APP_ID = ""
  VITE_FIREBASE_MEASUREMENT_ID = ""
  VITE_OPENAI_API_KEY = ""
  VITE_IKHOKHA_MERCHANT_ID = ""
  VITE_IKHOKHA_API_KEY = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200